name: Deploy
on: [push]

env:
  EB_VERSION_LABEL: github-${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
      - name: Format check
        working-directory: backend
        run: |
          black . --check
          flake8 . --max-line-length=88
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm install
      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
      - name: Move frontend files to backend
        run: |
          mkdir backend/static
          cp -r frontend/build/* backend/static
      - name: Check everything copied
        working-directory: backend/static
        run: |
          ls -l
      - name: Generate deploy file
        working-directory: backend
        run: zip -r ../deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET }}
            application_name: eb-django-test
            environment_name: deploy-env
            version_label: ${{ env.EB_VERSION_LABEL }}
            region: us-west-2
            deployment_package: deploy.zip
        